// <auto-generated />
using System;
using CocktailRecipeApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CocktailRecipeApp.Migrations
{
    [DbContext(typeof(CocktailDbContext))]
    [Migration("20250125172535_Seeding2")]
    partial class Seeding2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CocktailRecipeApp.Models.Cocktail", b =>
                {
                    b.Property<int>("CocktailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CocktailID"));

                    b.Property<string>("CocktailDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CocktailName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("GlassType")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ingredient")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("CocktailID");

                    b.ToTable("Cocktails");

                    b.HasData(
                        new
                        {
                            CocktailID = 1,
                            CocktailDescription = "A fruity and tropical cocktail made with passionfruit and vanilla vodka.",
                            CocktailName = "Passionfruit Martini",
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GlassType = 0,
                            ImagePath = "Images/PassionfruitMartini.jpg",
                            Ingredient = "2 oz Vanilla Vodka, 1 oz Passionfruit Puree, 1 oz Lime Juice, 1 oz Simple Syrup, Prosecco to serve",
                            Instructions = "Shake all ingredients except prosecco with ice. Strain into a martini glass and top with prosecco.",
                            IsFavourite = false,
                            Rating = 5
                        },
                        new
                        {
                            CocktailID = 2,
                            CocktailDescription = "A classic whiskey cocktail made with sugar, bitters, and citrus peel.",
                            CocktailName = "Old Fashioned",
                            DateAdded = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GlassType = 3,
                            ImagePath = "Images/OldFashioned.jpg",
                            Ingredient = "2 oz Bourbon or Rye Whiskey, 1 Sugar Cube, 2 Dashes Angostura Bitters, Orange Peel",
                            Instructions = "Muddle sugar cube and bitters in a glass. Add whiskey and ice, stir well. Garnish with orange peel.",
                            IsFavourite = false,
                            Rating = 4
                        },
                        new
                        {
                            CocktailID = 3,
                            CocktailDescription = "A stylish and tart cocktail with vodka, cranberry, and lime.",
                            CocktailName = "Cosmopolitan",
                            DateAdded = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GlassType = 0,
                            ImagePath = "Images/Cosmopolitan.jpg",
                            Ingredient = "1.5 oz Citrus Vodka, 1 oz Cranberry Juice, 0.5 oz Lime Juice, 0.5 oz Triple Sec",
                            Instructions = "Shake all ingredients with ice and strain into a chilled martini glass. Garnish with lime wedge.",
                            IsFavourite = true,
                            Rating = 5
                        },
                        new
                        {
                            CocktailID = 4,
                            CocktailDescription = "A refreshing cocktail with mint, lime, sugar, and rum.",
                            CocktailName = "Mojito",
                            DateAdded = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GlassType = 1,
                            ImagePath = "Images/mojito.png",
                            Ingredient = "Mint, Lime, Sugar, Rum, Soda Water",
                            Instructions = "Muddle mint and sugar, add lime juice, rum, and soda water.",
                            IsFavourite = false,
                            Rating = 5
                        },
                        new
                        {
                            CocktailID = 5,
                            CocktailDescription = "A classic tequila-based cocktail with lime and Cointreau.",
                            CocktailName = "Margarita",
                            DateAdded = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GlassType = 2,
                            ImagePath = "Images/margarita.jpg",
                            Ingredient = "Tequila, Lime Juice, Cointreau, Salt",
                            Instructions = "Shake ingredients with ice and serve in a salted rim glass.",
                            IsFavourite = true,
                            Rating = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
